[package]
name = "mimalloc_rust"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = ["mimalloc-sys"]

[dependencies]
mimalloc-sys = {path = "mimalloc-sys"}